# conda env create -f environment.yml
name: lume-services-project-template
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cookiecutter
  - versioneer
  - lume-model
  - pytablewriter
  - gitpython
  - jupyterlab
