name: Build docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    name:  Build docs
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          {% raw -%}
          python-version: ${{ matrix.python-version }}
          {%-endraw %}
          mamba-version: "*"
          channels: conda-forge
          activate-environment: {{ cookiecutter.project_slug }}-dev
          environment-file: dev-environment.yml

      - name: Install { cookiecutter.project_slug }}
        shell: bash -l {0}
        run: |
          pip install -e .
          
      - name: Build and deploy
        shell: bash -l {0}
        run: |
          mkdocs build
          mkdocs gh-deploy --force
