name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click
  - pydantic

  # dev
  - pre-commit
  - pytest
  - pytest-cov

  # docs
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
