name: {{ cookiecutter.repo_name }}-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click
  - pydantic
  - pip 
  - pip: 
    - git@github.com:jacquelinegarrahan/lume-services.git

  # dev
  - pre-commit
  - pytest
  - pytest-cov
