name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
dependencies:
  - prefect # until lume-services registered with conda
  - lume-model # until lume-services registered with conda
  - pip 
  - pip: 
    - git+https://github.com/slaclab/lume-services.git@main
